[package]
name = "Warlords"
version = "1.0.0"
authors = []

[addresses]
warlords_addr = "_"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }
